### ISSUE TITLE
Extra output on drush commands makes piping difficult

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#98] opened 2020-09-04 06:53 UTC
Each drush command outputs "Connection to my-site.test closed." to the end of it. This makes it very unpractical to pipe the output to other commands.

Some drush commands also start with extra output of "Starting drush on `mbb`" but this can be suppressed with `-q`. But I could not figure out how to silence the ssh output of closed connection.

**Example**

I want to check if `shortcut` module is enabled or not. I run command

`phab -cmbb drush pml|grep shortcut`

This outputs the status of `shortcut` module but the the command just hangs and never exits.

**Comment by stmh** [comment] 2020-09-07 15:52
hi @mikran 

I fixed the hang and silenced ssh, but besides that I cant reproduce the issue on my end. Changes are committed to develop branch, would be great if you can test it on your end (just clone the repo and run the command you want via `/my/absolute/url/to/phabalicious/bin/phab ...`

**Comment by mikran** [comment] 2020-09-08 06:53
> I fixed the hang and silenced ssh, but besides that I cant reproduce the issue on my end. Changes are committed to develop branch, would be great if you can test it on your end (just clone the repo and run the command you want via `/my/absolute/url/to/phabalicious/bin/phab ...`

It is fixed now. Thank you!

**Closed** 2020-09-08 13:38 UTC
Labels: bug
